### PR TITLE
Add OSRAM Chip LED packages

### PR DESCRIPTION
**Pull request by dbrgn**
Datasheets:

https://www.osram.com/os/products/index.jsp -> "LEDs for Automotive, Consumer and Industry Applications" -> "Low-power"

I added CHIPLED 0603 and CHIPLED 0805.

### CODE REVIEW

**Comment by HBadertscher** [comment]
What do you think about generic chip LED packages (0402, 0603, 0805, 1206)? There are very similar LEDs from many different manufacturers with more or less identical packages.

**Comment by dbrgn** [comment]
I'm not sure. Chip LEDs are not standardized and especially for LEDs there might be different footprints depending on the dissipated power.

For example the the 0402 CHIPLED by OSRAM looks very different than the 0603 and 0805 packages. And high power LEDs often have custom footprints too.

Therefore I'd stick to manufacturer specfic footprints that match the recommendations exactly.

**Comment by dbrgn** [comment]
(That doesn't mean that we can't also add generic packages + devices like we did for the resistors. But I wouldn't use the generic package for the manufacturer-specific devices though.)

**Comment by HBadertscher** [comment]
Sounds good to me. I think at least for the standard chip LEDs, generic devices and packages would make sense too, but we can add those separately later.

**Comment by dbrgn** [comment]
Oh, looks like I've miscalculated the silkscreen clearance. Will fix that tonight.

**Comment by dbrgn** [comment]
Clearance fixed.

**Comment by ubruhin** [comment]
Hmm yeah I think having both, generic and specific LED packages and devices is fine...

But IMHO we should have separate packages for every lens color, otherwise we can't assign proper 3D models later once 3D models are supported. So I'd suggest to put the color into the package name, e.g. "OSRAM CHIPLED 0805 Transparent" for packages with transparent lens.

**Comment by dbrgn** [comment]
@ubruhin fixed!

**Review by ubruhin — APPROVED** [review]

**Pull request merged**
